version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  cli:
    privileged: true
    image: wordpress:cli
    restart: always
    volumes:
      - wpcore:/var/www/html
      - ./bin:/var/www/html/bin
      - ~/.wp-content:/var/www/html/wp-content
      - ./dist/neve-pro-addon:/var/www/html/wp-content/plugins/neve-pro-addon
    depends_on:
      - mysql
      - wordpress
  wordpress:
    privileged: true
    ports:
      - 8081:80
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - wpcore:/var/www/html
      - ./bin:/var/www/html/bin
      - ~/.wp-content:/var/www/html/wp-content
      - ./dist/neve-pro-addon:/var/www/html/wp-content/plugins/neve-pro-addon
    restart: always
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_ROOT_PASSWORD=wordpress
      - WORDPRESS_DEBUG=1
volumes:
  wpcore: